package vault.ui;

import vault.domain.Vault;

import javax.swing.*;
import java.awt.*;

public class NewVaultDialog extends JDialog {

    private final JTextField titleField = new JTextField(25);
    private final JTextField urlField = new JTextField(25);
    private final JTextField usernameField = new JTextField(25);
    private final JTextArea descriptionArea = new JTextArea(4, 25);
    private final JPasswordField passwordField = new JPasswordField(25);

    Vault result;

    NewVaultDialog(Window owner) {
        super(owner, "New Vault", Dialog.ModalityType.APPLICATION_MODAL);

        JPanel form = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();

        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        int row = 0;

        gbc.gridx = 0;
        gbc.gridy = row;
        form.add(new JLabel("Title"), gbc);
        gbc.gridx = 1;
        form.add(titleField, gbc);

        row++;
        gbc.gridx = 0;
        gbc.gridy = row;
        form.add(new JLabel("URL"), gbc);
        gbc.gridx = 1;
        form.add(urlField, gbc);

        row++;
        gbc.gridx = 0;
        gbc.gridy = row;
        form.add(new JLabel("Username"), gbc);
        gbc.gridx = 1;
        form.add(usernameField, gbc);

        row++;
        gbc.gridx = 0;
        gbc.gridy = row;
        form.add(new JLabel("Password"), gbc);
        gbc.gridx = 1;
        form.add(passwordField, gbc);

        row++;
        gbc.gridx = 0;
        gbc.gridy = row;
        form.add(new JLabel("Description"), gbc);
        gbc.gridx = 1;
        form.add(new JScrollPane(descriptionArea), gbc);

        JButton saveButton = new JButton("Save");
        JButton cancelButton = new JButton("Cancel");

        saveButton.addActionListener(e -> save());
        cancelButton.addActionListener(e -> dispose());

        JPanel buttons = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttons.add(cancelButton);
        buttons.add(saveButton);

        add(form, BorderLayout.CENTER);
        add(buttons, BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(owner);
    }

    public void save() {
        long now = System.currentTimeMillis();

        result = new Vault(
                0, // generated by DB
                titleField.getText().trim(),
                urlField.getText().trim(),
                usernameField.getText().trim(),
                descriptionArea.getText().trim(),
                new String(passwordField.getPassword()), // encrypt before saving
                "",
                now,
                now
        );

        dispose();
    }

    public Vault getResult() {
        return result;
    }
}
